#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# waybar
# $scripts/launch_waybar &
waybar &
$scripts/tools/dynamic &

# wallpaper
# effects
$scripts/rgb &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &



# Idle daemon to screen lock
# hypridle &

swayidle -w before-sleep 'hyprlock -c ~/.config/hypr/hyprlock.conf' &

hyprpaper &

# tlp start &

export GTK_THEME=Catppuccin-Mocha &
# export GDK_DPI_SCALE=1.5 &
export GDK_SCALE=1.5 &