'\" t
.\"     Title: swaylockd
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.15
.\"      Date: 2021-09-08
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "SWAYLOCKD" "1" "2021-09-08" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
swaylockd \- launch swaylock(1) and re\-launch if it dies
.SH "SYNOPSIS"
.sp
All arguments are directly passed to \fBswaylock(1)\fP.
.SH "DESCRIPTION"
.sp
\fBswaylockd\fP is a dumb launcher to spawn \fBswaylock(1)\fP and ensure it\(cqs running no matter what \(em it immediately restarts \fBswaylock(1)\fP if terminated by a signal (e.g. the process crashed) and also blocks all signals (except \f(CRSIGKILL\fP and \f(CRSIGSTOP\fP).
It also ensures that only one instance per user is running (using \fBflock(2)\fP).
.sp
\fBIMPORTANT\fP: \fBswaylockd\fP is not compatible with \fBswaylock(1)\fP option \fB\-\-daemonize\fP!
.SH "ENVIRONMENT"
.sp
\fBXDG_RUNTIME_DIR\fP
.RS 4
This variable must be set and contain the path to the existing directory where the lock file will be created.
Refer to \(lqXDG Base Directory Specification\(rq for more information.
.RE
.SH "FILES"
.sp
\fB${XDG_RUNTIME_DIR}/swaylockd.lock\fP
.RS 4
A lock file created when \fBswaylockd\fP is executed and removed right before it quits.
.RE
.SH "LOGGING"
.sp
Error messages generated by \fBswaylockd(1)\fP are printed to STDERR and logged to syslog with ident string \(lqswaylockd\(rq and facility code 1 (user).
.SH "HISTORY"
.sp
\fBswaylockd\fP has been developed mainly as a workaround for the \fBswaylock(1)\fP stability issues (see e.g. issue \c
.URL "https://github.com/swaywm/swaylock/issues/181" "#181" ")."
.sp
\fBswaylock(1)\fP is a critical piece of security software \(em as a screen locker, any bug in the program that causes it to crash will cause the screen to unlock.
As soon as \fBswaylock(1)\fP is no longer running, the screen is no longer locked.
Therefore, great care must be taken to ensure that it never crash.
.SH "AUTHORS"
.sp
Jakub Jirutka
.SH "REPORTING BUGS"
.sp
Report bugs to the project\(cqs issue tracker at \c
.URL "https://github.com/jirutka/swaylockd/issues" "" "."
.SH "SEE ALSO"
.sp
\fBswaylock(1)\fP